name: Deploy mkosi

on:
  push:
    branches: [ "tanit" ]
    paths:
      - 'mkosi/**'
      - '.github/workflows/mkosi.yml'
      - '.github/workflows/reusable.yml'
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  call-docker-publish:
    uses: ./.github/workflows/reusable.yml
    with:
      dockerfile: mkosi/Containerfile
      name: "mkosi"
      description: "mkosi, for building elementary OS images"
