name: Deploy xorriso

on:
  push:
    branches: [ "tanit" ]
    paths:
      - 'xorriso/**'
      - '.github/workflows/xorriso.yml'
      - '.github/workflows/reusable.yml'
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  call-docker-publish:
    uses: ./.github/workflows/reusable.yml
    with:
      dockerfile: xorriso/Containerfile
      name: "xorriso"
